### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by harpone** [Ryo-Ito/spatial_transformer_network#1]
Hi! Nice code! I was thinking of using your interpolation code (in our company's repo), but you don't currently have a license... could you add a license (preferably an open source one naturally)?

I have my own TF interpolation function, but your's is a lot nicer :)

**Comment by Ryo-Ito** [comment]
I am actually not familiar with code licenses. As it says in the README.txt, my code is a modified version. The original one has a license and the interpolation part is almost the same.
Doesn't the original code meet your requirement?

**Comment by harpone** [comment]
Ah, OK I'll refer to the original code then. Thanks!
